version: '3.5'
services:
  php:
    build: ./config/docker/php
    container_name: repo-php
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: "php -S 0.0.0.0:8123"
    ports:
      - "127.0.0.1:8123:8123"
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "2"